---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: seaopolis
    app.kubernetes.io/instance: seaopolis
  name: seaopolis
  namespace: seaopolis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seaopolis
  template:
    metadata:
      labels:
        app: seaopolis
    spec:
      nodeSelector:
        worker: "true"
      containers:
        - env:
            - name: EULA
              value: 'TRUE'
            - name: MOD_PLATFORM
              value: 'AUTO_CURSEFORGE'
            - name: CF_API_KEY
              value: '$$2a$$10$$glYS2Cf8Igq09KL2RmIta.D.2kUm5UBBKm3RlMqcmkFPj6jP/3EH6'
            - name:  CF_SLUG
              value: 'seaopolis-submerged'
            #- name:  CF_FILENAME_MATCHER
              #value: '9.1.11'
            #- name: CF_SERVER_MOD
              #value: '/download/seaopolis.zip'
            - name: ALLOW_FLIGHT
              value: 'TRUE'
            - name: 'MEMORY'
              value: '32G'
          image: itzg/minecraft-server
          name: seaopolis-server
          ports:
            - containerPort: 25565
          resources:
            limits:
              memory: 32Gi
            requests:
              memory: 32Gi
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /data
              name: seaopolis
      restartPolicy: Always
      volumes:
        - name: seaopolis
          persistentVolumeClaim:
            claimName: seaopolis
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: seaopolis
  name: seaopolis
  namespace: seaopolis
spec:
  ports:
  - name: seaopolis-tcp
    port: 25565
    protocol: TCP
    targetPort: 25565
  selector:
    app: seaopolis
  loadBalancerIP: 10.1.40.15
  type: LoadBalancer
