---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: allthemods9
    app.kubernetes.io/instance: allthemods9
  name: allthemods9
  namespace: allthemods9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allthemods9
  template:
    metadata:
      labels:
        app: allthemods9
    spec:
      nodeSelector:
        worker: "true"
      containers:
        - env:
            - name: EULA
              value: 'TRUE'
            - name: MOD_PLATFORM
              value: 'AUTO_CURSEFORGE'
            - name: CF_API_KEY
              value: '$$2a$$10$$glYS2Cf8Igq09KL2RmIta.D.2kUm5UBBKm3RlMqcmkFPj6jP/3EH6'
            - name:  CF_SLUG
              value: 'all-the-mods-9'
            #- name:  CF_FILENAME_MATCHER
              #value: '9.1.11'
            #- name: CF_SERVER_MOD
              #value: '/download/allthemods9.zip'
            - name: ALLOW_FLIGHT
              value: 'TRUE'
            - name: 'MEMORY'
              value: '32G'
          image: itzg/minecraft-server
          name: allthemods9-server
          ports:
            - containerPort: 25565
          resources:
            limits:
              memory: 32Gi
            requests:
              memory: 32Gi
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /data
              name: allthemods9
      restartPolicy: Always
      volumes:
        - name: allthemods9
          persistentVolumeClaim:
            claimName: allthemods9
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: allthemods9
  name: allthemods9
  namespace: allthemods9
spec:
  ports:
  - name: allthemods9-tcp
    port: 25565
    protocol: TCP
    targetPort: 25565
  selector:
    app: allthemods9
  loadBalancerIP: 10.1.40.13
  type: LoadBalancer
