---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vanilla-minecraft
    app.kubernetes.io/instance: vanilla-minecraft
  name: vanilla-minecraft
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vanilla-minecraft
  template:
    metadata:
      labels:
        app: vanilla-minecraft
    spec:
      nodeSelector:
        worker: "true"
      containers:
        - env:
            - name: EULA
              value: 'TRUE'
            - name: ALLOW_FLIGHT
              value: 'TRUE'
            - name: 'MEMORY'
              value: '32G'
          image: itzg/minecraft-server
          name: vanilla-minecraft
          ports:
            - containerPort: 25565
          resources:
            limits:
              memory: 10Gi
            requests:
              memory: 10Gi
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /data
              name: vanilla-minecraft
      restartPolicy: Always
      volumes:
        - name: vanilla-minecraft
          persistentVolumeClaim:
            claimName: vanilla-minecraft
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vanilla-minecraft
  name: vanilla-minecraft
  namespace: minecraft
spec:
  ports:
  - name: vanilla-minecraft-tcp
    port: 25565
    protocol: TCP
    targetPort: 25565
  selector:
    app: vanilla-minecraft
  loadBalancerIP: 10.1.40.30
  type: LoadBalancer
